nextcloud/password_policy

js/settings-admin.js

@LukasReschke you were a little bit to fast? I just wanted to add this additional small fix to the pr... :wink: 
Doesn't break anything but the semicolons should still be there.

add  missing semicolon

---

README.md

backport of #8 
For the sake of completeness 😜 @schiessle

[stable9] add a README file

---

js/settings-admin.js
lib/PasswordPolicyConfig.php
templates/settings-admin.php
tests/lib/controller/PasswordPolicyConfigTest.php

For https://github.com/nextcloud/server/issues/735
CC: @LukasReschke @jancborchardt @MorrisJobke @schiessle @icewind1991

Release polishing (minimal length + input validation)

---

README.md
appinfo/info.xml
templates/settings-admin.php

cc @LukasReschke @rullzer 
for nextcloud/server#735

fix casing of Password policy app

---

README.md
appinfo/info.xml
templates/settings-admin.php

cc @LukasReschke @rullzer
for nextcloud/server#735

[stable10] fix casing of Password policy app

---

js/settings-admin.js
lib/PasswordPolicyConfig.php
templates/settings-admin.php
tests/lib/controller/PasswordPolicyConfigTest.php

Backport of #17 
For https://github.com/nextcloud/server/issues/735
CC: @MorrisJobke @schiessle

[Stable10] Release polishing (minimal length + input validation)

---

img/app.svg

As disccussed in nextcloud/server#856
@nextcloud/designers

Added app icon from core/action password.svg

---

.travis.yml

Better testing

---

l10n/.tx/config

add transifex

---

templates/settings-admin.php

cc @rullzer @nickvergessen 
ref https://github.com/nextcloud/server/pull/1948

Fix PHPDoc for IL10n

---

lib/PasswordPolicyConfig.php
tests/lib/controller/PasswordPolicyConfigTest.php
tests/lib/controller/PasswordValidatorTest.php

NIST recommends a minimum of 8 characters

Follow nist password length recommendations

---

appinfo/app.php
appinfo/info.xml
lib/AppInfo/Application.php

* Created a real Application.php
* Only query for all the required components when we receive the event
- Saves always loading the l10n stuff for example
* Use DI magic to resolve dependencies

Make app more lazy

---

js/settings-admin.js

* OC.AppConfig => OCP.AppConfig
* == => ===

Cleanup js

---

lib/AppInfo/Application.php
lib/Capabilities.php

expose password_policy settings as capabilities so that other programs can make use of it.

add capabilities

---

appinfo/app.php
lib/AppInfo/Application.php
lib/Capabilities.php
lib/PasswordPolicyConfig.php
lib/PasswordValidator.php
lib/Settings.php

Make the app strict

---

css/settings-admin.css
js/settings-admin.js
lib/PasswordPolicyConfig.php
lib/PasswordValidator.php
lib/Settings.php
templates/settings-admin.php
tests/lib/controller/PasswordValidatorTest.php

[13] Allow to check against haveibeenpwned.com password list

---

templates/settings-admin.php

Fix for #64
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

Fixed typo

---

.travis.yml
tests/lib/PasswordPolicyConfigTest.php
tests/lib/PasswordValidatorTest.php
tests/lib/Validator/CommonPasswordsValidatorTest.php
tests/lib/Validator/LengthValidatorTest.php
tests/lib/Validator/NumericCharacterValidatorTest.php
tests/lib/Validator/SpecialCharactersValidatorTest.php
tests/lib/Validator/UpperCaseLowerCaseValidatorTest.php

Update master php testing versions

---

lib/Validator/HIBPValidator.php

See: https://haveibeenpwned.com/API/v3#PwnedPasswordsPadding

Support the new HIBP add padding

---

css/settings-admin.css
js/settings-admin.js
lib/AppInfo/Application.php
lib/HistoryCompliance.php
lib/PasswordPolicyConfig.php
lib/PasswordValidator.php
lib/Settings.php
lib/Validator/IValidator.php
templates/settings-admin.php
tests/lib/HistoryComplianceTest.php

brings in a password hash-based password history per user, if a history > 0 is configured. 
defaults to 0 (= disabled)

test against password history, if configured

---

appinfo/info.xml
js/settings-admin.js
lib/AppInfo/Application.php
lib/FailedLoginCompliance.php
lib/Listener/FailedLoginListener.php
lib/Listener/SuccesfullLoginListener.php
lib/PasswordPolicyConfig.php
lib/Settings.php
templates/settings-admin.php

Disable account after failed login attempts

---

lib/ComplianceService.php

Else wrong user/password attempts generate an exception

---

lib/PasswordValidator.php
lib/Validator/LengthValidator.php
lib/Validator/NumericCharacterValidator.php

Console:
```
occ user:resetpassword admin
Enter a new password: 
Confirm the new password: 
Password needs to be at least 8 characters long. Password needs to contain at least one lower and one upper case character. Password needs to contain at least one special character. Password is present in compromised password list. Please choose a different password.
```
Web reset:
Web change:
Styling isn't the best everywhere, but that needs fixing in server.
Fix #59

Check all password requirements in one attempt

---

README.md

Fixes #113 
Signed-off-by: Christian Hartmann <chris-hartmann@gmx.de>

Fix default password length

---

lib/PasswordPolicyConfig.php
tests/lib/PasswordPolicyConfigTest.php

Set default password policy length to 10

---

package-lock.json

Like https://github.com/nextcloud/password_policy/pull/407 for stable25

[stable25] Update loader-utils from 1.4.0 to 1.4.2 and 2.0.2 to 2.0.4

---

.github/workflows/command-compile.yml
.github/workflows/command-rebase.yml
.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/lint-eslint-when-unrelated.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node-when-unrelated.yml
.github/workflows/node.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/phpunit-summary-when-unrelated.yml
composer.json
composer.lock

chore(CI): Update master php testing versions and workflow templates

---

.github/workflows/phpunit-mysql.yml
appinfo/info.xml
package-lock.json
package.json

feat(deps): Add Nextcloud 29 support on master

---

appinfo/info.xml
package-lock.json
package.json

feat(deps): Add Nextcloud 30 support on master

---

appinfo/info.xml
package-lock.json
package.json

feat(deps): Add Nextcloud 31 support on master

---

.github/CODEOWNERS
.github/workflows/openapi.yml
.gitignore
REUSE.toml
composer.json
lib/Capabilities.php
lib/Controller/APIController.php
lib/PasswordPolicyConfig.php
openapi.json
tests/lib/Validator/CommonPasswordsValidatorTest.php
vendor-bin/openapi-extractor/composer.json
vendor-bin/openapi-extractor/composer.lock

- Required for Talk frontend and clients with https://github.com/nextcloud/spreed/pull/13767

feat: Add OpenAPI

---

.github/workflows/phpunit-sqlite.yml

chore(CI): Adjust testing matrix for Nextcloud 31 on stable31

---

.github/workflows/block-merge-eol.yml
.github/workflows/block-merge-freeze.yml
.github/workflows/command-compile.yml
.github/workflows/dependabot-approve-merge.yml
.github/workflows/fixup.yml
.github/workflows/lint-eslint.yml
.github/workflows/lint-php-cs.yml
.github/workflows/lint-php.yml
.github/workflows/lint-stylelint.yml
.github/workflows/node.yml
.github/workflows/phpunit-mariadb.yml
.github/workflows/phpunit-mysql.yml
.github/workflows/phpunit-oci.yml
.github/workflows/phpunit-pgsql.yml
.github/workflows/phpunit-sqlite.yml
.github/workflows/pr-feedback.yml
.github/workflows/reuse.yml

[stable30] ci(github): Update workflows

---

composer.lock

| Dev Changes     | From    | To      | Compare                                                             |
|-----------------|---------|---------|---------------------------------------------------------------------|
| symfony/process | v5.4.36 | v5.4.47 | [...](https://github.com/symfony/process/compare/v5.4.36...v5.4.47) |

[stable30] Update symfony/process
